eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: ADDRESS-SERVICE